<?php

########################################################################
# Extension Manager/Repository config file for ext: "nnfesubmit"
#
# Auto generated by Extension Builder 2014-10-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NN Frontend Submission',
	'description' => 'Datensätze für News, Kalender etc. im Frontend posten und durch einen Redakteur freigeben lassen',
	'category' => 'plugin',
	'author' => 'David Bascom',
	'author_email' => 'david@99grad.de',
	'author_company' => '99grad',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>